apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-user

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: test-binding
subjects:
  - kind: ServiceAccount
    name: test-user
    namespace: test
roleRef:
  kind: Role
  name: solr-operator-leader-election-role
  apiGroup: rbac.authorization.k8s.io
