{{- range $user := .Values.users }}
{{- range $role := $user.roles }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $user.name }}-{{ $role.name }}
  namespace: {{ $role.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $role.name }}
subjects:
- kind: ServiceAccount
  name: {{ $user.name }}
  namespace: {{ $role.namespace }}

---
{{- end }}
{{- end }}
